version: 2
jobs:
  build:
    docker:
      - image: circleci/node:4-browsers
    steps:
      - checkout
      - run: npm install
      - run: echo "hello world"
  test:
    docker:
      - image: circleci/node:4-browsers
    steps:
      - checkout
      - run: npm run lint
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
